#! /bin/bash
set -e

CLOUDFLARE_PAGES_PROJECT=seanblanchfield-blog

function echo_green() {
    echo -e "\033[32m$1\033[00m"
}

COMMON_SCRIPT_PATH="$(realpath ${BASH_SOURCE[0]})"
COMMON_SCRIPT_DIR="$(dirname $COMMON_SCRIPT_PATH)"
DOCKER_IMAGE="blog"

USER_ID="$(id -u)"
GROUP_ID="$(id -g)"


ENV_VARS="--env JEKYLL_UID=$USER_ID --env JEKYLL_GID=GROUP_ID --env JEKYLL_ENV=production"

# VOLUME_MOUNTS="--volume $COMMON_SCRIPT_DIR/_config.yml:/blog/_config.yml --volume $COMMON_SCRIPT_DIR/source:/blog/source --volume $COMMON_SCRIPT_DIR/public:/blog/public "
VOLUME_MOUNTS="--volume $COMMON_SCRIPT_DIR:/srv/jekyll"

if ! which wrangler > /dev/null; then
    echo "Could not find wranger. This is required to deploy to cloudflare. Please install with:"
    echo "sudo npm install -g wrangler"
    echo "and then run `wrangler login`"
    exit -1
fi

if [[ "$1" == "docker_build" ]]; then
    docker build . -t $DOCKER_IMAGE --no-cache
elif [[ "$1" == "shell" ]]; then
    docker run --rm  -it \
        $VOLUME_MOUNTS  \
        $ENV_VARS \
        --entrypoint="bash" \
        $DOCKER_IMAGE:latest

elif [[ "$1" == "deploy" ]]; then
    echo_green "Rebuilding site..."
    docker run --rm  -it \
        $VOLUME_MOUNTS  \
        $ENV_VARS \
        $DOCKER_IMAGE:latest \
        jekyll build

    if [[ -n "$(git status --porcelain )" ]]; then
        echo_green "Committing and pushing changes"
        git add -A  && git commit -m "CLI deployment"
        git push
    else
        echo_green "Skipping push, as there are no changes detected."
    fi

    echo_green "Deploying site..."
    docker run --rm \
        -v $COMMON_SCRIPT_DIR/public:/public \
        --env-file=.env \
        jez500/wrangler:latest \
            pages publish \
                --project-name $CLOUDFLARE_PAGES_PROJECT \
                /public

    echo_green "Done."

elif [[ "$1" == "serve" ]]; then
    echo_green "Serving locally..."
    docker run --rm -it \
        $VOLUME_MOUNTS \
        $ENV_VARS \
        --publish 4000:4000 \
        $DOCKER_IMAGE:latest \
        jekyll \
        serve \
        --host \
        0.0.0.0

else
    docker run --rm -it \
        $VOLUME_MOUNTS \
        $ENV_VARS \
        --publish [::1]:4000:4000 \
        $DOCKER_IMAGE:latest \
        jekyll \
        $@
fi
